### ISSUE TITLE
Add the docker image to the GitHub image registry

### ISSUE THREAD

**Issue by btschwertfeger** [btschwertfeger/BiasAdjustCXX#28]
**Is your feature request related to a problem? Please describe.**
GitHub provides a space to store docker images. These are shown on the right side of the repository under the optional "packages" entry. 

Solution proposal:
```yaml
# publish_ghcr.yaml
name: Publish GHCR
on:
  push:
    branches:
      - "master"
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.username }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/btschwertfeger/BiasAdjustCXX:latest
          docker run ghcr.io/btschwertfeger/BiasAdjustCXX:latest
          docker push ghcr.io/btschwertfeger/BiasAdjustCXX:latest
```
